# Generated by Django 4.0.3 on 2022-04-01 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 1, 13, 17, 37, 411533, tzinfo=utc)),
        ),
    ]
