# Generated by Django 4.0.3 on 2022-04-11 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 11, 19, 56, 40, 764060, tzinfo=utc)),
        ),
    ]
