# Generated by Django 4.0.3 on 2022-04-11 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 11, 20, 9, 11, 731829, tzinfo=utc)),
        ),
    ]
