HOME_PAGE_ROUTE = 'home.html'
HOUSE_PAGE_ROUTE = 'house_view/mine_page.html'
GLOBAL_PAGE_ROUTE = 'global/global.html'
GLOBAL_PAGE_CITY_DROPDOWN_ROUTE = 'global/city_dropdown.html'
LOGIN_PAGE_ROUTE = 'login/login.html'
