# Generated by Django 4.0.3 on 2022-03-30 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Mortgage', 'Mortgage'), ('bills', 'Bills'),
                                                       ('Transportation', 'Transportation'), ('Clothing', 'Clothing'),
                                                       ('Healthcare', 'Healthcare'), ('Food', 'Food'),
                                                       ('Insurance', 'Insurance'), ('Kids', 'Kids'),
                                                       ('Culture', 'Culture'), ('Vacations', 'Vacations'),
                                                       ('Other', 'Other')], default='Other', max_length=32)),
            ],
        ),
    ]
