# Generated by Django 4.0.3 on 2022-04-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='author',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tip',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
