# Generated by Django 4.0.3 on 2022-03-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_test_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Tip',
        ),
    ]
