TIPS_PAGE_ROUTE = 'tips/index.html'
ADD_TIP_PAGE_ROUTE = 'tips/add_tip.html'
EDIT_TIP_PAGE_ROUTE = 'tips/edit_tip.html'
READ_MORE_PAGE_ROUTE = 'tips/read_more.html'
CATEGORIES_PAGE_ROUTE = 'tips/categories.html'
DATE_PAGE_ROUTE = 'tips/filtered_by_date.html'
SHOW_PROFILE_ROOT = 'accounts/show_profile.html'
