# Generated by Django 4.0.3 on 2022-03-27 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0003_delete_job_alter_city_id_alter_country_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('story_text', models.TextField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
            ],
        ),
    ]
