# Generated by Django 4.0.3 on 2022-05-13 18:31

from django.db import migrations
from django.core.management import call_command

fixtures = ['countries_cities']


def load_fixture(apps, schema_editor):
    call_command('loaddata', *fixtures)


class Migration(migrations.Migration):
    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
