# Generated by Django 4.0.3 on 2022-03-31 10:42

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_delete_job_alter_city_id_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='children',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='income',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
